container: 'termoshtt/flat_ffi_example:latest'
pool:
  vmImage: 'ubuntu-16.04'
steps:
  - checkout: self
    submodules: true
  - script: |
      cmake -Bbuild -H.
      make -C build -j
    displayName: Build C++ library
  - script: |
      mv test.py build
      cd build
      pytest-3 test.py
    displayName: Test Python binding
