container: 'ubuntu:18.04'
pool:
  vmImage: 'ubuntu-16.04'
steps:
  - script: |
      apt update
      apt install -y g++ make cmake libboost-all-dev libpython3-dev python3-numpy
    displayName: apt install
    privileged: true
  - script: |
      cmake -Bbuild -H.
      make -C build -j
    displayName: build
