pool:
  vmImage: 'ubuntu-16.04'
steps:
  - script: |
      sudo apt update
      sudo apt instal -y cmake python3
    displayName: apt install
  - script: |
      cmake -Bbuild -H.
      make -C build -j
    displayName: build
